### ISSUE TITLE
Resource detail

### ISSUE THREAD

**Issue by martinnec** [martinnec/kgbrowser#4]
When the user single-clicks on a node, a detail of the resource represented by the node is displayed in the resource detail area of the knowledge graph browser.

The data for the detail is loaded by calling the `detail` method on the server. The current view of the node is supplied as the `view` parameter.

The data for the detail loaded from the server is displayed as a two-columns table with the first column containing the name of a data property and the second column containing the value of the data property.

A property is displayed as link with the propety IRI.

There is also the full label of the node representing the resource displayed as a heading at the top of the detail area. It is a link with the resource IRI.

Further, the detail contains a list of all views for the resource. This list is loaded from the server by calling the `view-sets` method. The current view for the resource is highlighted. The user may change here the current view.

If no current view has been selected by the user for the resource yet, the default one is chosen as the current view.

Changing the current view does not affect the current views of other displayed resources.

**Comment by sstenchlak** [comment]
Mohl bych se zeptat, jak mám interpretovat odpověď ze serveru na `view-sets`, kde jednotlivé `views` patří pod `viewSets`, které mají `iri` a `label`? Znamená to tedy, že jeden resource může mít více `vewSets` a každý z nich má své vlastní `views`?

**Comment by martinnec** [comment]
Ano, je to tak. Jedná se o logické sdružování views do skupin na straně serveru. Můžete to využít pro uspořádání views, které dostanete jako odpověď, do skupinek.
