### ISSUE TITLE
Resource filtering by graph properties

### ISSUE THREAD

**Issue by martinnec** [martinnec/kgbrowser#8]
Displayed resources can be filtered by various graph properties. More different graph properties will be considered in the future. For now, the following filters must be provided to the user:

- Show nodes with a degree in a given interval
- Show nodes with an incomming degree in a given interval
- Show nodes with an outgoing degree in a given interval

The nodes which are filtered out are hidden. Each hidden nodes behaves as described in #6 .

**Comment by sstenchlak** [comment]
Již jsem začal pracovat na návrhu, který jsem zmínil i ke konci Skype hovoru. Chtěl bych se zeptat, jak moc ho mám zachovat, nebo změnit:

- Graf si udržuji ve "stromovité struktuře", kde kořenem jsou počáteční vrcholy a hranami jsou jednotlivé expanze.
- Smazat (uvolnit z paměti) mohu pouze kořenové vrcholy, nebo celé expanze. Jakmile dojde ke smazání, k některým uzlům mohu ztratit referenci, pak se smažou i tyto uzly. Tedy mám počáteční vrchol, ten expanduji a nějaké syny expanduji dále, smazáním původní expanze se smažou i všechny dceřiné. - To má dle mého názoru výhodu v tom, když se při prohlížení grafu vydám špatnou cestou a potřebuji se vrátit o několik kroků zpět.
- Kromě mazání mohu i skrývat. Zde platí, že můžu skrývat jednotlivé vrcholy, nebo expanze, nebo použít **filtry na expanzi** (které pak vlastně skryjí některé vrcholy). Opět i zde se děje to, že nemohu-li se dostat k některému vrcholu přes viditelné vrcholy, bude také skryt.

Samozřejmě tento přístup nemusím použít, pokud budete chtít, každopádně mi alespoň způsob mazání, jak jsem popsal výše, přijde intuitivní.

Pokud bychom dovolili mazat expanze tak, že se smažou jen vrcholy z konkrétní expanze, časem v grafu může vzniknout velké množství samostatných vrcholů, které pak půjdou těžko smazat.

Taktéž filtrování konkrétních expanzí může být přínosné, například filtrováním expanze u počátečního vrcholu podle typu vrcholu nám schová i vrcholy vzniklé z aktuálně pro nás nezajímavých vrcholů a graf se tímto značně zjednoduší.

Otázkou tedy je, jak to spojit s vašim požadavkem na filtry, které jsou aplikovány na celý graf. Určitě nebude problém udělat stejnou logiku i tady, že vrcholy, ke kterým se z počátečního vrcholu nedostanu (ve smyslu přes expanze, nikoli po skutečných hranách grafu) budou skryty. Možná ale zde bude typičtější případ, že budu chtít skrýt jen ty vrcholy, co určí filtr. Nebo můžu tuto featuru udělat volitelnou.

Nebude to již příliš překombinované? Hlavně tedy při aplikaci vašich (globálních) filtrů se může stát, že budu-li mazat nějaký vrchol, smažou se i na první pohled nesouvisející právě díky tomu, že globální filtr zastíní.

Ptám se hlavně proto, že toto dost ovlivní jádro mé aplikace a v budoucnu by se to už hůře měnilo.

**Comment by martinnec** [comment]
Popisované chování mi přijde správné a intuitivní. Možná je to trochu komplikovanější pro uživatele, ale myslím, že je to to, co uživatel očekává. Je ale otázkou, zda vždy chce provést kompletní smazání/schování - viz konec tohoto mého komentáře.

Nejprve vyjasnění, zda chápu správně, co píšete (když tak korigujte):

1) Pokud vložím do grafu nový uzel, zakládám tedy vrchol toho expanzního stromu. Expanzí uzlu vytvářím pod vrcholem další vrcholy a takto rekurzivně. Pokud vložím do grafu další uzel jinak než expanzí jiného, zakládám nový vrchol nového expanzního stromu.

2) Podle #6 mohu vybraný jeden uzel U schovat. Tomuto uzlu odpovídá nějaký uzel V v nějakém expanzním stromu. Schování uzlu znamená též schování všech uzlů, kterým odpovídá podstrom uzlu V, tj. uzly, které se do grafu dostaly expanzí U nebo expanzí (rekurzivně) uzlu, do kterého jsem se dostal z expanze U.

3) Podobně mazání uzlu.

4) Můj požadavek na filtrování uzlů pak vlastně znamená jen, že místo jednoho uzlu schováváme nebo mažeme více uzlů a pro každý aplikujeme chování 2), resp. 3).

Nyní k tomu, zda vždy chci provést kompletní smazání/schování. Představte si např. tu konfiguraci k Registru práv a povinností. Ta mi umožňuje se např. z Orgánu veřejné moci (=úřadu) A dostat přes expanze k jinému Orgánu veřejné moci B. Pokud bych smazal A, smaže se i B, OK? Pokud ano, nemusí to být vždy OK chování (přičemž někdy může). Někdy může chtít uživatel opravdu jen smazat A (a samozřejmě hrany s ním asociované). Jindy může chtít schovat vše z něj expandované až po B, ale nikoliv B - např. proto, že hledá B, ale neví jak na něj ale ví, že se k němu nějak dostane přes A. Takže začíná u A, ale jen s cílem, aby nakonec v obrázku grafu měl B.  Jindy může uživatel chtít smazat opravdu i B, resp. komplet expanzi A.

Nemyslím tedy, že je správné nabídnout jen možnost smazat vše. Obdobně pro schovat. Probírali jsme to ještě ve skupině a napadlo nás, že by se ten expanzní strom využil ne pro mazání/schovávání přímo, ale pro selekce uzlů. Co by to znamenalo:

1) Vyberu uzly klikáním nebo filtrem (tj. filtr by pak nebyl přímo určen k mazání/schovávání, ale jen k výběru uzlů). Tj. vyberu n uzlů.

2) V případě, kdy je vybrán alespoň jeden uzel, zobrazí se někde viditelně volba "Přidat do výběru expanze uzlů", "Smazat výběr", "Schovat výběr" (např. formou tlačítka npod.). 

3) Pokud vyberu volbu "Přidat do výběru expanze", přidají se do výběru kompletní expanze všech uzlů, které již jsou ve výběru.

4) Pokud nějaký vybraný uzel odstraním z výběru (např. kliknutím), nástroj se mě zeptá, zda chci z výběru odstranit i expanzi tohoto uzlu nebo jen ten uzel.

5) Pokud kliknu na "Smazat výběr" nebo stisknu tlačítko "Delete", provede se smazání vybraných uzlů (ale nikoliv už jejich expanzí automaticky - uzly v expanzi předchozí interakcí buďto jsou nebo nejsou ve výběru).

6) Pokud kliknu na "Schovat výběr", provede se schování vybraných uzlů.

**Comment by sstenchlak** [comment]
Chápete správně, možná jen doplním, že se skrývají/mažou jen ty vrcholy, ke kterým se nedá dostat z žádného vrcholu, který je kořenem expanzního stromu. Tedy mám-li dva vrcholy A a B, oba expanduji a shodou okolností mi oba vyrobí stejný vrchol V (například dva ministerstva vykonávají stejnou agendu), pak smazáním vrcholu A se vrchol V nesmaže (i když je vlastně přímým potomkem v expanzním stromu) protože je stále součástí expanze vrcholu B.

Vlastně se nejedná o strom, ale o orientovaný graf (který může být cyklický) s tím, že některé vrcholy považuji za "kořenové". Vždy, jak nějaký vrchol smažu/skryji, rozhlídnu se ze všech kořenových vrcholů a pokud se do nějakého vrcholu nedokážu dostat, tak jej taky smažu/skryji. Ale měl jsem to uloženo tak, že to vypadalo jako několik stromů jejichž kořeny byly ony kořenové vrcholy. Omlouvám se za špatné vyjádření, pokud jsem vás zmátl.

Jak jste popisoval problém s hledáním orgánu veřejné moci, tedy že chci zanechat pouze tento vrchol, stačilo by jej prohlásit za vrchol expanzního stromu a původní vrchol smazat.

Každopádně pokud je cílem si spíš s grafem více hrát a mazat jednotlivé vrcholy, pak můj přístup nepůjde použít, s tím souhlasím a udělám to jinak. Je pravda, že já jsem spíš cílil na to, že se při procházení vydám do hloubky, poté se zase vrátím (a smažu všechny expanze), vydám se jiným směrem atp.

Stále si tedy můžu pamatovat expandované vrcholy ke každému vrcholu a dle toho vybírat vrcholy na smazání, ale už nebudu moci provádět tak dynamické filtrování expanzí jak jsem sliboval (protože nevím, kdo je čím vlastníkem; již nemá smysl si pamatovat kořenové vrcholy, protože když odstraním nějaký vrchol, tak bych musel všechny vrcholy vzniklé z jeho expanze považovat taky za kořenové, aby se nesmazaly a to už kazí tu ideu, že si vlastně uživatel zvolil na začátku nějaké kořenové a jen "odsekává podstromy", které ho nezajímají).

Jediný problém, který je spíše z UX, vidím v tom, jak se vlastně budou vrcholy mazat. Představte si, že mám dva ministerstva a jejich expanzí dostanu agendy. Některé agendy bych například mohl dále expandovat.

Nyní bych chtěl uklidit a zde hodně záleží, jakým způsobem, ale kdybych chtěl smazat jen jedno ministerstvo, tak dává smysl mazat i jeho agendy, ale otázkou které? Protože některé mohou být sdíleny s druhým ministerstvem. Zde vidím problém v tom, že aplikace nepozná, co vše chce uživatel vlastně smazat (protože ne vždy může být situace tak moc jednoduchá a může například obsahovat vrcholy, které se expandují do cyklu) a tedy se může stát, že po špatném smazání vznikne hodně malých nesouvislých grafů (například pokud ministerstvo s agendami, ale zapomenu zahrnout i jejich expanze).

Nevím, jestli toto ignorovat, nebo to nějak řešit, co myslíte?

**Comment by martinnec** [comment]
To, co popisujete mi nepřijde v rozporu s chováním 1-6 výše. Když vyberu uzel / uzly kliknutím nebo filtrem, mohu říci, že chci i expanze těchto vybraných uzlů. Nástroj přidá do výběru i kompletní expanze. Já pak mohu některé uzly z výběru odstranit. Což mi přijde jako řešení UX problému, který popisujete.
